development:
    twitter_consumer_key: 'ppQ1p1AXbtvxC9qTR6PsfJppW'
    twitter_consumer_secret: 'YMWmCr2oeFSdQkbxFhyS6qdI4BIuvV7iZFQxSIbyP2exIlK0Xu'
    twitter_access_token:  '174534564-v29cIDBrl0VCQnoUyuvMCuDOmRDLHDPGpmwRNwrr'
    twitter_access_token_secret: 'IMQJwQeEtqeR1q8AnJhRehFaVikyXdyROfQD1DJ9lcYck'

production:
    twitter_consumer_key: 'tnfz3yBPrWXevxAnvYDXaJcFc'
    twitter_consumer_secret: '3RctkYQxJovDBimWCzaHi2t2SvkgFxw3XKpn3KdUYDRFa0ypGM'
    twitter_access_token:  '174534564-burDP0Yw79eMC2UKYsDCHMQ6W66t4D5tZyqrKkzm'
    twitter_access_token_secret: 'DBIBxesMmM3i3lKvOzEs6YARUz2COGo3XBdB6jPgzlEM6'
