development:
    twitter_consumer_key: 'ppQ1p1AXbtvxC9qTR6PsfJppW'
    twitter_consumer_secret: 'YMWmCr2oeFSdQkbxFhyS6qdI4BIuvV7iZFQxSIbyP2exIlK0Xu'
    twitter_access_token:  '174534564-v29cIDBrl0VCQnoUyuvMCuDOmRDLHDPGpmwRNwrr'
    twitter_access_token_secret: 'IMQJwQeEtqeR1q8AnJhRehFaVikyXdyROfQD1DJ9lcYck'

production:
    twitter_consumer_key: 'brCBkgTdY2nAucSCMhaycUBeq'
    twitter_consumer_secret: 'SkvxXX2fi6zOGzcRTocqyCVNGTsOy53VGzKHuxlXGcSZK6TQqc'
    twitter_access_token:  '174534564-T356UCpSZXEZubhIwbXxFd0LJqG6LRf9CU53QmmH'
    twitter_access_token_secret: 'H3U4tICwf93oUa1NdD5fMxVFACKNuoAp6FoGqLTCcsEir'
